# Numpy'a dair

In [1]:
import numpy as np

- Shape

- size

- ndim

- reshape

- resize

- dtype

In [68]:
array=np.array([[1,2,3],[4,5,6]])
print("shape",array.shape)
print("size = ",array.size)
print("ndin",array.ndim)
print("dtype",array.dtype)
array_=array.reshape(3,2)
array.resize(3,2)#resize ve reshape farkı= resize ile yapılan değişiklilk kalıcıdır. reshape ilee yapılıan değişiklik kalıcı değildir değişkene atanmalısdır
print("resahpe",array.shape)
print("resize",array.shape)
print("size = ",array.size)
print("ndin",array.ndim)
array

shape (2, 3)
size =  6
ndin 2
dtype int64
resahpe (3, 2)
resize (3, 2)
size =  6
ndin 2


array([[1, 2],
       [3, 4],
       [5, 6]])

- zeros

- ones

- empty

In [16]:
a=np.zeros((2,2),dtype="int64")
b=np.ones((3,2))
c=np.empty((2,3))

print(a)
print()
print(b)
print()
print(c)

[[0 0]
 [0 0]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


- arange
- linespace

In [25]:
#normal py nin kemdisindeki range gibi. ama bu array yapıyor range array yapmaz
#np.arange(x,y,z) x'ten y'ye z'şer adım :)
#linspace ise belli araşıkta kaç tane seçeceğini soylersin o secer bir nevi random 
#np.linespace(x,y,z) x-y arasında z adet number
a1=np.arange(1,10,2)
a2=np.linspace(1,10,6,dtype="int64")
print(a1)
print()
print(a2)


[1 3 5 7 9]

[ 1  2  4  6  8 10]


- liste

- tolist

In [38]:
#hocam liste ve array farklı neden çünkü biri liste diğeri array :))
#array metodlarını listede kullanamazsın. liste metodlarınıda array dde kullanamaazsınn tabiki :))
list=[1,2,3,4,5,6]
array=np.array([1,2,3,4,5,6])#hocam dikkat ettiniz mi? array oluşturmka iiçin n.array metodununiçine liste yazıyoruz
array_=array.tolist()

print(list)
print()
print(array)
print()
print(array_)

[1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]

[1, 2, 3, 4, 5, 6]


pointer gibşi hepsi aynı yeri tutuyor :))


In [42]:
d=a
b=c
a=c

c=[1,2,3,4]

a[2]


3

- -1 'in gücü [::-1]
- copy
- ravel

In [67]:
# [::-1]  ters  çeviirir
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([1,2,3,4])
a2_ters=a2[::-1]
a_ters=a[::-1]
print(a2_ters)
print(a_ters)


print(a[-1:])
print(a[:-1])

#-1 sonuncu sütün/satırı seçer :))



a_1=a.ravel()
a_1.shape

#rave tek boyutlu hale getirir

[4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]]
[[1 2 3]
 [4 5 6]]


(9,)

- tranpoze T

In [70]:
print(a)
print()
a.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])